<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTerminalcountTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
		// Table to store the count of receipts allowed for a terminal
        Schema::create('terminalcount', function (Blueprint $table) {
            $table->bigIncrements('id');
			// FK to opos_terminal.id
            $table->integer('terminal_id')->unsigned();
			// The number of receipts that is allowed for this terminal
            $table->integer('allowed_receipt_count')->unsigned()->nullable();
			// The current receipt count of receipts
			// that has been generated by this terminal
            $table->integer('current_rcount')->unsigned()->nullable();
            $table->softDeletes();
            $table->timestamps();
            $table->engine = "ARIA";
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('terminalcount');
    }
}
