truncate module;
insert into module (slug,name,description,created_at,updated_at) values('stg','settings','Setting',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('loc','location','Location',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('data','data','Data',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('dmgmt','dmgmt','Data Management',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('alli','alli','Alliance',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('umgmt','umgmt','User Management',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('fnch','franchise','Franchise',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('prcu','procure','Procurement',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('csgn','consign','Consignment',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('prod','product','Product',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('ana','analytics','Analytics',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('cash','cash','Cash',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('stk','stock','Stock Level',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('oper','operator','Operator View',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('job','job','Job Management',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('rpt','report','Report',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('grp','group','Group Relationship',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('conso','consoreport','Consolidated Report',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('crep','comreport','Company Report',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('rvpy','recvpay','Receivable Payable',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('vcab','vcab','VirtualCabinet',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('auto','auto','Auto',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('man','manual','Manual',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('pgn','pigeon','Pigeon',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('ind','industry','Industry',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('oilg','oilgas','Oil & Gas',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('mall','mall','Mall',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('autm','automobile','Automobile & Automotive',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('ecom','ecommerce','E-Commerce',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('insr','insurance','Insurance & Brokerage',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('comm','commission','Commission',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('snm','snm','Services & Maintenance',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('ast','asset','Asset',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('tts','tts','Trouble Ticketing Service',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('repr','repair','Repair',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('wrnt','warranty','Warranty',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('cmr','cmr','Corrective Maintenance Report',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('csr','csr','Crane Service Report',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('cpcr','cpcr','Crane Preventive Check Report',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('prdt','production','Production',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('dist','distribution','Distribution',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('cadm','centraladmin','Central Administration',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('logs','logistics','Logistics & Warehouse',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('dlvr','deliveryman','Deliveryman Management',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('vhc','vehicle','Vehicle Management',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('drum','drumbarrel','Drum & Barrel',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('ret','retail','Retail',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('mbr','membership','Membership',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('opos','opossum','OPOSsum',now(),now());
-- insert into module (slug,name,description,created_at,updated_at) values('wast','wastage','Wastage & Damage',now(),now());
-- insert into module (slug,name,description,created_at,updated_at) values('prom','promo','Promo Definition',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('indt','industrial','Industrial',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('crm','crm','CRM',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('humn','human','HumanCap',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('stf','staff','Staff',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('schd','scheduler','Scheduler',now(),now());
insert into module (slug,name,description,created_at,updated_at) values('attd','attendance','Attendance Report',now(),now());
