insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(1,'Gilbarco Veeder Root',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(2,'Start Italiana SMT-XMT',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(3,'Petrovend4',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(4,'Struna Kedr spec. 1.4',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(5,'Fafnir Visy-Quick',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(6,'Assytech',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(7,'ATG Simulator',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(8,'Hectronic HLS',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(9,'UniProbe',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(10,'Vega',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(11,'Windbell',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(12,'Accu',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(13,'Humanentec',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(14,'Labkotec',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(15,'Qingdao Guihe Modbus',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(16,'Lemis Process Modbus RTU',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(17,'Dut-E COM',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(18,'Gilbarco DIM',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(19,'Petrovend4 ACR',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(20,'TLS Input',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(21,'ND UUS-1',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(22,'Alisonic Delphi',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(23,'Sensor Sens',now(),now());
insert into og_probe_protocol (protocol_no, protocol_name, created_at, updated_at) values(24,'Fafnir Torrix RS-485',now(),now());
